sudo: required
services:
  - docker

before_install:
  - docker build -t rishabh75/docker-fibo -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rishabh75/docker-fibo npm run test

after_success:
  - docker build -t rishabh75/multi-client ./client
  - docker build -t rishabh75/multi-nginx ./nginx
  - docker build -t rishabh75/multi-server ./server
  - docker build -t rishabh75/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rishabh75/multi-client
  - docker push rishabh75/multi-server
  - docker push rishabh75/multi-nginx
  - docker push rishabh75/multi-worker

deploy:
  deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-984330943620"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
